Repository CLOVER-energy/CLOVER, pull requests merged in 2022-08, with the labels that each got.

#103 :tada: New citation and manifest files
  CITATION.cff
  MANIFEST.in
Labels: enhancement

#96 54 prioitise self generation bug
  src/clover/simulation/storage.py
  src/clover/tests/integration/test_clover.py
Labels: bug

#106 🚀 Release v5.0.4 of CLOVER to `master`
  CITATION.cff
  README.md
  setup.cfg
  src/clover/__main__.py
  src/clover/simulation/energy_system.py
  src/clover/simulation/storage.py
  src/clover/tests/integration/temp_location/inputs/scenario/scenario_inputs.yaml
  src/clover/tests/integration/test_clover.py
Labels: bug

#76 :rocket: Deploy PV-T changes to dev branch
  .gitattributes
  .github/workflows/mypy.yml
  .gitignore
  .pylintrc
  README.md
  UPDATE REGISTER.rtf
  bin/test-clover.sh
  locations/Bahraich/inputs/optimisation/optimisation_inputs.yaml
  requirements.txt
  setup.cfg
  src/clover/__main__.py
  src/clover/__utils__.py
  src/clover/analysis.py
  src/clover/conversion/conversion.py
  src/clover/fileparser.py
  src/clover/generation/solar.py
  src/clover/impact/__utils__.py
  src/clover/impact/finance.py
  src/clover/impact/ghgs.py
  src/clover/load/load.py
  src/clover/optimisation/__utils__.py
  src/clover/optimisation/appraisal.py
  src/clover/optimisation/optimisation.py
  src/clover/optimisation/single_line_simulation.py
  src/clover/simulation/__utils__.py
  src/clover/simulation/diesel.py
  src/clover/simulation/energy_system.py
  src/clover/simulation/solar.py
  src/clover/simulation/storage.py
  src/clover/src/new_location.yaml
  src/clover/tests/integration/test_clover.py
Labels: enhancement, feature

#109 Update CITATION.cff
  CITATION.cff
Labels: documentation

#115 Add .zenodo.json
  .zenodo.json
Labels: documentation

#118 116 unmet diesel
  .zenodo.json
  CITATION.cff
  setup.cfg
  src/clover/__main__.py
  src/clover/__utils__.py
  src/clover/simulation/diesel.py
  src/clover/simulation/energy_system.py
Labels: enhancement

#121 Remove related identifiers
  .zenodo.json
Labels: bug

#124 122 power consumption attribution
  setup.cfg
  src/clover/__main__.py
  src/clover/impact/__utils__.py
  src/clover/impact/finance.py
  src/clover/impact/ghgs.py
  src/clover/optimisation/appraisal.py
  src/clover/simulation/solar.py
Labels: bug

#125 Improve HPC Optimisation Process
  .github/pull_request_template.md
  outbox_assembly_script.py
  src/clover/__main__.py
  src/clover/argparser.py
  src/clover/fileparser.py
  src/clover/optimisation/__utils__.py
  src/clover/optimisation/optimisation.py
  src/clover/optimisation/single_line_simulation.py
  src/clover/scripts/hpc.py
  src/clover/scripts/hpc_utils.py
Labels: enhancement, HPC

#127 Files for submission to the JOSS
  paper.bib
  paper.md
Labels: documentation

#129 Move HPC outbox assembly script to scripts
  outbox_assembly_script.py
  setup.cfg
  src/clover/scripts/clover_hpc_outbox_assembly.py
  src/clover/scripts/hpc_outbox_assembly.py
Labels: enhancement
